# -*- coding: utf-8 -*-
"""Day2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PuaByHLdjMiZeGIbaNqe-FbSlLWKZaAb
"""

#list and its default functions

lst = ["Apple","Mango","orange"]
lst

#Append
lst.append("banana")
lst

#Copy
x=lst.copy()
x

#Count
a=lst.count("Mango")
a

num=[1,2,3,4]
num

#Extend
lst.extend(num)
lst

#Index
lst.index(3)

#Insert
lst.insert(3,"lycheee")
lst

#Pop
lst.pop(6)

lst

#Remove
lst.remove("banana")
lst

#Reverse
lst.reverse()
lst

num1=[9,3,5,7,0]
num1

#Sort
num1.sort()
num1

lst1=["lychee","orange","Apple"]
lst1

lst1.sort()
lst1

#Dictionary and its functions

dit={"Brand":"Realme",
      "Model":"6pro",
      "Price":"14999"}
dit

#Copy
b=dit.copy()
b

#fromkeys
a=('key1','key2','key3')
b=2
x=dit.fromkeys(a,b)
x

#get
s=dit.get("Model")
s

#Items
z=dit.items()
z

#Keys
a=dit.keys()
a

dit.pop("Price")
dit

#sets and its default functions

st={"python","realme","letsupgrade",12,16}
st

#Add
st.add("Doll")
st

#Copy
a=st.copy()
a

#Difference
st1={"Apple","letsupgrade","sai",14,46}
x=st.difference(st1)
x

#Difference_update
st.difference_update(st1)
st

#Discard
st.discard("Doll")
st

#Intersection
st={"python","letsupgrade",12,16}
st1={"python","letsupgrade",12,49}
s=st.intersection(st1)
s

#Isdisjoint
st={"python","letsupgrade",12,16}
st1={"p","joy",1}
d=st.isdisjoint(st1)
d

#Pop
st.pop()
st

#Tuple and its default function

tup=("keyboard","mouse","cpu")
tup

tup.count("cpu")

tup.index("keyboard")

#Strings and its methods

string="Python"
string

string="Hello welcome to letsupgrade,lets learn new things in letsupgrade"
b=string.count("letsupgrade")
b

string="Hii iam {fname}"
print(string.format(fname="Robot"))

string="Hii iam Robot"
print(string.index("iam"))

string="hii guys iam robot"
s=string.capitalize()
s

string.casefold()

